- demos/040-pagination-dynamic.html
- src/jade/api/pagination/params.jade
added some documentation for dynamicMainBullets.
also integrated the variable into an existing example so users will be aware that it's possible to modify the number of visible main bullets
need to update the code in dist so the functionality will work,
i guess you will do it when you'll create new release
> dynamicMainBullets documentation + integration into existing example

- src/jade/api/zoom/intro.jade
> Fix typo on Zoom's example

- src/jade/_internal-template.jade
- src/jade/api/index.jade
> prepare mixin for edit link in the API docs

- src/jade/index/index.jade
> Fix typo on homepage

- src/pug/api/params.pug
See https://github.com/nolimits4web/swiper/pull/3283
> Document centeredSlidesBounds parameter

- README.md
- src/pug/index.pug
- Fixed a number of grammatical mistakes on the homepage
- Added `alt` and `title` attributes to logo images near the bottom of the homepage
- Updated README to reflect the switch from Jade to Pug and use the new website URL
Cheers!
> Fixed a few grammatical mistakes and updated README

- public/i/stackblitz-icon.svg
- src/pug/demos/index.pug
Hi, I've opened today an [issue with proposal](https://github.com/nolimits4web/swiper-website/issues/49) to make demos in stackblitz.
So in this PR I added 15 first demos with link to stackblitz edit. [Example](https://stackblitz.com/edit/swiper-demo-14-centered-slides-auto-slides-per-view?file=index.html)
I could do all the demos, but I afraid if you wont approve PR and then it would be just waste of time :)
let me know if you want me to make all other demos.
> Stackblitz demos

- src/pug/api/hash-navigation/events.pug
- https://github.com/nolimits4web/swiper/blob/master/CHANGELOG.md#swiper-540---released-on-may-15th-2020
- https://github.com/nolimits4web/swiper/blob/master/src/components/hash-navigation/hash-navigation.js
> Fix typos in Hash Navigation Events

- src/pug/react/index.pug
New PR with change only to pug file
> Added swiper-react tutorial video *NEW PR*

- src/pug/react/index.pug
> Update index.pug for React

- src/pug/api/effect-flip/params.pug
- src/pug/api/props-methods.pug
- src/pug/vue/index.pug
Fix typo (Similar to the one already fixed by @cseas  for the React version)
Also removed the reference to the runCallbacks parameter from the updateAutoHeight method in "props-methods.pug" and rotate parameter from flipEffect in "params.pug"
> Update index.pug for Vue

- src/pug/api/events.pug
> Added doubleClick in events.pug

- src/pug/get-started/index.pug
- Small typo in an import statement.
> Fix small typo in import statement

- src/pug/api/thumbs/params.pug
> Fixed typo in params.pug

- package.json
> Fixed year on the release date of v6.4.6

- src/components/Footer.js
- src/components/FooterSponsors.js
- src/components/GithubStats.js
- src/components/HomeSlider.js
- src/components/HomeSponsors.js
- src/components/SidebarSponsors.js
- src/pages/demos.js
- src/pages/index.js
- src/pages/sponsors.js
https://web.dev/external-anchors-use-rel-noopener/?utm_source=lighthouse&utm_medium=devtools
lighthouse suggestion
> fix: add rel="noopener" to external links

- src/pages/swiper-api.mdx
PR created for the issue mentioned here: https://github.com/nolimits4web/swiper/issues/4167
This is something reported a lot of times, so maybe updating the documentation can help.
> docs(fade): update documentation

- src/pages/get-started.mdx
- src/pages/react.mdx
- src/pages/svelte.mdx
- src/pages/swiper-api.mdx
> fix: install modules import

- src/pages/swiper-api.mdx
> Fixed typos in swiper-api.mdx

- demos/src/dynamic/200-infinite-loop.js
- demos/src/dynamic/210-infinite-loop-with-slides-per-group.js
> fix: typo Inifinite

- src/pages/angular.mdx
- src/pages/react.mdx
- src/pages/svelte.mdx
- src/pages/swiper-api.mdx
- src/pages/vue.mdx
Update angular.mdx, react.mdx, svelte.mdx, swiper-api.mdx and vue.mdx
> Fixed typos Coveflow / Overflow -> Coverflow

- src/pages/swiper-api.mdx
Update swiper-api.mdx
"_srscet_" -> "**srcset**"
> fix: srcset typo

- src/pages/angular.mdx
> fix(angular): SwiperComponent type missing

- package-lock.json
- package.json
- src/components/ApiDivider.js
- src/components/Footer.js
- src/components/FooterSponsors.js
- src/components/Header.js
- src/components/Heading.js
- src/components/HomeHeader.js
- src/components/HomeProjects.js
- src/components/HomeSlider.js
- src/components/HomeSponsors.js
- src/components/PageHeader.js
- src/components/SidebarSponsors.js
- src/components/TableOfContents.js
- src/components/ThemeToggle.js
- src/layouts/withSidebar.js
- src/pages/_document.js
- src/pages/demos.js
- src/pages/index.js
- src/pages/sponsors.js
- src/styles/base.css
- src/styles/demos.css
- src/styles/docs.css
https://tailwindcss.com/blog/automatic-class-sorting-with-prettier
> feat: tailwind Automatic Class Sorting with Prettier

- src/pages/vue.mdx
Fix https://github.com/nolimits4web/swiper-website/issues/210
> Fix slot syntax

- build/api/build-methods.js
- build/api/build-options.js
https://github.com/nolimits4web/swiper-website/issues/169
> fix(types): handling array types in api docs

- build/api/build-events.js
- build/api/build-methods.js
- build/api/build-options.js
https://github.com/nolimits4web/swiper-website/pull/215#issuecomment-1024196421
> fix(types): handle `null` in docs

- package.json
> Fixed the year of the version 8.0.0 release date

- src/pages/get-started.mdx
> Update swiper@7 to swiper@8 in get-started.mdx

- src/pages/swiper-api.mdx
> Update notice for v8 migration in swiper-api.mdx

- src/pages/get-started.mdx
> Fix API documentation link

- src/pages/angular.mdx
- src/pages/react.mdx
- src/pages/svelte.mdx
- src/pages/vue.mdx
Update angular.mdx, react.mdx, svelte.mdx and vue.mdx
> Fixed `api` -> `swiper-api`

- build/api/description.js
> fix: api function descriptions

- src/layouts/withSidebar.js
link: https://github.com/nolimits4web/swiper-website/edit/master/src/pages/{path}.mdx
should it open in a new tab?
> feat: edit this page on github

- src/demos/330-hash-navigation/react/src/App.jsx
Missing module import
Currently it does not work
> Update HashNavigation demo

- src/pages/index.js
> Fix Typo in index.js

- src/pages/migration-guide-v9.mdx
> fix: correct spelling errors

- public/sponsors-list.json
- src/pages/demos.js
- src/shared/codesandbox.js
button will be more relevant, as it is not a link (especially for a11y)
> fix(a11y): change demos link to button

- src/pages/element.mdx
> Fix typo "lowecase"

- src/demos/300-thumbs-gallery/vue/src/App.vue
Hello!
At the moment there is an error due to which the code does not work, it must be removed here 'value'
> Superfluous "value"

- src/pages/element.mdx
Angular has full support for web components, including passing attributes as props and listening for custom events:
```ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { register } from 'swiper/element/bundle';
import { Swiper } from 'swiper/types';
register();
@Component({
selector: 'my-component',
template: `
<swiper-container
slides-per-view="3"
space-between="spaceBetween"
centered-slides="true"
[pagination]="{ hideOnClick: true }"
[breakpoints]="{
'768': {
slidesPerView: 3
}
}"
(swiperprogress)="onProgress($any($event))"
(swiperslidechange)="onSlideChange()"
>
<swiper-slide>Slide 1</swiper-slide>
<swiper-slide>Slide 2</swiper-slide>
<swiper-slide>Slide 3</swiper-slide>
</swiper-container>
`,
schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class MyComponent { …
```
> docs: add angular usage

- src/shared/codesandbox.js
[Screencast from 24-07-25 23:44:59.webm](https://github.com/user-attachments/assets/2320f92a-0262-4c7f-bb26-e94ce8eea0c4)
you can view in there or https://swiperjs.com/demos visit the page and click codesandbox buttons and view the preloader i fixed them
> fix: preloader fixed
